M48
; DRILL file {KiCad 8.0.1} date 2025-04-02T13:34:05-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-02T13:34:05-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.980
%
G90
G05
T1
X151.587Y-53.567
X151.587Y-56.567
T2
X150.99Y-69.37
M30
